name: ctop
channels:
  - conda-forge
dependencies:
  # Python and scientific libraries
  - python=3.10
  - h5py
  - scipy
  - matplotlib
  - pandas
  - uproot
  - seaborn
  - pytest
  - jsonschema
  
  # General libraries and tools
  - parallel
  - gxx=13.3.0  # Compiler
  - gcc=13.3.0
  - openmpi
  - hdf5
  - zlib
  - doxygen
  - gsl=2.7.1
  - cmake
  - eigen=3.4.0
  - yaml-cpp
  
  # Boost (specific version)
  - boost=1.78.0
  - boost-cpp=1.78.0
  
  # ROOT (no GUI/display dependencies needed)
  - root_base
  - ca-certificates
  - openssl
