"""Helpers for per-event jet sampling (utils/sample_dijets -> CCAKE).

Pure file-format functions live here so they can be unit tested without
running the chain: writing the sample_dijets INI config and converting its
CSV output into the jets file CCAKE reads (`hydro.jets.input_mode: file`).
"""
import csv


def write_sample_dijets_config(path, ampt_dir, vertex_source, sqrts_gev,
                               pt_min, pt_max, n_dijets, csv_file, tau_hydro):
    """Write the INI config consumed by utils/sample_dijets/sample_dijets."""
    with open(path, 'w') as f:
        f.write("# generated by the chain wrapper (jets_sampling)\n")
        f.write("[input]\n")
        f.write(f"ampt_dir = {ampt_dir}\n")
        f.write(f"vertex_source = {vertex_source}\n\n")
        f.write("[pythia]\n")
        f.write(f"sqrts = {sqrts_gev}\n")
        f.write(f"pt_min = {pt_min}\n")
        f.write(f"pt_max = {pt_max}\n\n")
        f.write("[sampling]\n")
        f.write(f"n_dijets = {n_dijets}\n\n")
        f.write("[output]\n")
        f.write(f"csv_file = {csv_file}\n")
        f.write(f"tau_hydro = {tau_hydro}\n")
    return path


def dijets_csv_to_ccake_jets(csv_path, out_path):
    """Convert sample_dijets CSV output into a CCAKE jets input file.

    CCAKE's file reader takes one jet per line as whitespace-separated
    `x y eta pT phi rapidity` (lines starting with '#' are skipped). The CSV
    already contains BOTH partons of every dijet, so the resulting file must
    be used with `hydro.jets.auto_partner: false`.

    Returns the number of jet rows written.
    """
    n = 0
    with open(csv_path, newline='') as f_in, open(out_path, 'w') as f_out:
        f_out.write("# converted from sample_dijets CSV (both dijet partons listed)\n")
        f_out.write("# x[fm] y[fm] eta_s pT[GeV] phi rapidity\n")
        for row in csv.DictReader(f_in):
            f_out.write("{:.8f} {:.8f} {:.8f} {:.8f} {:.8f} {:.8f}\n".format(
                float(row['x_vtx']), float(row['y_vtx']), float(row['eta_s']),
                float(row['pT']), float(row['phi']), float(row['y'])))
            n += 1
    if n == 0:
        raise ValueError(f"no jet rows found in {csv_path}")
    return n


def energy_to_gev(value, unit):
    """Convert a collision energy given as (value, unit) to GeV."""
    scale = {'MeV': 1e-3, 'GeV': 1.0, 'TeV': 1e3}
    if unit not in scale:
        raise ValueError(f"Unknown energy unit: {unit}")
    return value * scale[unit]
