#!/usr/bin/env python
"""Regenerate the per-module 'all options' reference configs from schema.yml.

Each module gets one config here listing EVERY flag from the wrapper schema with
its real default value and description as a comment. These are generated (never
hand-written) so nothing is ever missed or drifts from the schema.

Run after changing wrapper/utils/schema.yml:

    python configs/all_options/regenerate.py
"""
import os
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SCHEMA = yaml.safe_load(open(os.path.join(REPO, 'wrapper', 'utils', 'schema.yml')))
OUTDIR = HERE

INPUT = SCHEMA['properties']['input']['properties']


def yval(v):
    """Format a Python value as a valid inline YAML scalar/flow node."""
    s = yaml.safe_dump(v, default_flow_style=True, width=10**9).strip()
    while s.endswith('...'):
        s = s[:-3].strip()
    return s


def leaf_value(node):
    """Pick a value to show for a scalar/array leaf: default, else representative."""
    if 'default' in node:
        return yval(node['default']), False
    if 'enum' in node:
        return yval(node['enum'][0]), True
    t = node.get('type')
    if t == 'array':
        mn = node.get('minItems', 0)
        if mn:
            item = node.get('items', {}) or {}
            idef = item.get('default')
            if idef is None:
                it = item.get('type')
                idef = 'default' if it == 'string' else (0 if it in ('number', 'integer') else None)
            return yval([idef] * mn), True
        return '[]', True
    if t in ('number', 'integer'):
        return '0', True
    if t == 'boolean':
        return 'false', True
    return '""', True


def emit(props, indent, lines):
    pad = '  ' * indent
    for key, node in props.items():
        if not isinstance(node, dict):
            continue
        desc = node.get('description', '')
        if node.get('type') == 'object' and 'properties' in node:
            if desc:
                lines.append(f"{pad}# {desc}")
            lines.append(f"{pad}{key}:")
            emit(node['properties'], indent + 1, lines)
        else:
            val, no_default = leaf_value(node)
            parts = []
            if desc:
                parts.append(desc)
            if 'enum' in node:
                parts.append("options: [%s]" % ", ".join(str(e) for e in node['enum']))
            if no_default:
                parts.append("[no schema default]")
            comment = ("  # " + " | ".join(parts)) if parts else ""
            lines.append(f"{pad}{key}: {val}{comment}")


def allof_then(stage_node, const):
    for sub in stage_node.get('allOf', []):
        cond = sub.get('if', {}).get('properties', {})
        for _k, c in cond.items():
            if c.get('const') == const:
                return sub['then']['properties']
    return {}


def params_of(stage_node, const):
    return allof_then(stage_node, const).get('parameters', {}).get('properties', {})


GLOBAL = """global:
  output: <REPLACE:/path/for/results>
  tmp: <REPLACE:/path/for/scratch>
  basedir: <REPLACE:/path/to/test_chain>
  nevents: 1
  grid:
    x_max: 12.0
    y_max: 12.0
    eta_max: 6.0
    step_x: 0.2
    step_y: 0.2
    step_eta: 0.2     # >0 -> 3+1D, 0 -> 2+1D
  energy:
    value: 5.02
    unit: TeV
  tau_hydro: 1.0
  ion_A: Pb
  ion_B: Pb
"""


def header(module, role):
    return (
        f"# ALL {module} OPTIONS — exhaustive schema reference ({role}).\n"
        f"# Every {module} flag from wrapper/utils/schema.yml, with its default value\n"
        f"# and description. This is a FLAG CATALOG (schema defaults shown, not a\n"
        f"# physics-tuned run): copy the keys you need into a runnable chain config\n"
        f"# from examples/. Auto-generated by regenerate.py; validates against the schema.\n"
    )


def write_stage(fname, module, role, stage_key, type_value, props,
                params_wrapped=True):
    lines = [header(module, role), GLOBAL, "input:", f"  {stage_key}:",
             f"    type: {type_value}"]
    if params_wrapped:
        lines.append("    parameters:")
        emit(props, 3, lines)
    else:
        emit(props, 2, lines)
    with open(os.path.join(OUTDIR, fname), 'w') as f:
        f.write("\n".join(lines) + "\n")
    nkeys = sum(1 for l in lines if ':' in l and not l.strip().startswith('#'))
    print(f"  {fname:28s} ~{nkeys} keys")


def main():
    IC, OV, PRE = INPUT['initial_conditions'], INPUT['overlay'], INPUT['preequilibrium']
    HY, PA, AB, AN = (INPUT['hydrodynamics'], INPUT['particlization'],
                      INPUT['afterburner'], INPUT['analysis'])

    print("regenerating configs/all_options/ :")
    write_stage('trento.yaml', 'TRENTo', 'initial condition',
                'initial_conditions', 'Trento', params_of(IC, 'Trento'))
    write_stage('ampt.yaml', 'AMPT', 'initial condition',
                'initial_conditions', 'ampt', params_of(IC, 'ampt'))
    write_stage('iccing.yaml', 'ICCING', 'overlay',
                'overlay', 'ICCING', params_of(OV, 'ICCING'))
    write_stage('amptgenesis.yaml', 'AMPTGenesis', 'overlay',
                'overlay', 'AMPTGenesis', params_of(OV, 'AMPTGenesis'))
    write_stage('freestreaming.yaml', 'FREESTREAMING', 'preequilibrium',
                'preequilibrium', 'freestreaming',
                {k: v for k, v in PRE['properties'].items() if k != 'type'},
                params_wrapped=False)
    write_stage('ccake.yaml', 'CCAKE', 'hydrodynamics',
                'hydrodynamics', 'CCAKE',
                {k: v for k, v in HY['properties'].items() if k != 'type'},
                params_wrapped=False)
    write_stage('is3d.yaml', 'iS3D', 'particlization',
                'particlization', 'is3d', params_of(PA, 'is3d'))
    write_stage('bqssampler.yaml', 'BQSSampler', 'particlization',
                'particlization', 'BQSSampler', params_of(PA, 'BQSSampler'))
    write_stage('analytical.yaml', 'ANALYTICAL', 'particlization',
                'particlization', 'analytical', params_of(PA, 'analytical'))
    write_stage('smash.yaml', 'SMASH', 'afterburner',
                'afterburner', 'smash', params_of(AB, 'smash'))
    write_stage('afterdecays.yaml', 'AFTERDECAYS', 'afterburner',
                'afterburner', 'afterdecays', params_of(AB, 'afterdecays'))
    write_stage('qvector_writter.yaml', 'QVECTOR_WRITTER', 'analysis',
                'analysis', 'qvector_writter',
                AN['properties'].get('parameters', {}).get('properties', {}))
    print("done.")


if __name__ == '__main__':
    main()
